### ISSUE TITLE
[BUG]-Auto 32k 

### ISSUE THREAD

**Issue by cmk-Destro** [C10udburst/meteor-rejects#25]
Auto 32k doesn't work,
in hopper mode it doesn't place and in dispenser mode the shulker doesn't go it to the dispenser.
pls fix

**Comment by cmk-Destro** [comment]
*UPDATE*
hopper mode doesn't open GUI 
dispenser mode randomly rotates the dispenser

**Comment by C10udburst** [comment]
@cmk-Destro auto32k works for me after https://github.com/C10udburst/meteor-rejects/commit/44d12f2b2c912c75e0ccffcc003ecedda6ca7a4b. Could you check if it works for you as well?

**Comment by C10udburst** [comment]
I'll assume it's fixed as there has been no response for 13 days.
