### ISSUE TITLE
Unbuildable src of 1.16.5

### ISSUE THREAD

**Issue by CheFuls** [C10udburst/meteor-rejects#27]

**Comment by StormyBytes** [comment]
We won't fix issues with the 1.16.5 version.

**Comment by C10udburst** [comment]
As said above, we don't support 1.16.5.
[Here](https://github.com/C10udburst/meteor-rejects/releases/download/latest-1.16/meteor-rejects-addon-0.0.4.jar) you can download the last build of 1.16.5 version.
