### ISSUE TITLE
[Bug] Fix skeleton ESP not working for fake players

### ISSUE THREAD

**Issue by C10udburst** [C10udburst/meteor-rejects#5]
don't check using uuid bruh

**Comment by necrophili** [comment]
Nor does it work with yourself. It also does not have the Nametags colors (or friends colors) meteor has for their ESP.  There is also a bug where if multiple players are standing close to each other and only one of them swing their arm, all of their Skeleton ESP would also swing their arm.

(Love this addon btw)

**Comment by C10udburst** [comment]
> Nor does it work with yourself.

I know. It doesn't, because it looks bad in first person
