### ISSUE TITLE
[Bug] Auto Wither

### ISSUE THREAD

**Issue by necrophili** [C10udburst/meteor-rejects#8]
I think auto wither source code player utils are broken af cuz of the new meteor 0.4.4 update, correct me if im wrong tho.

**Comment by necrophili** [comment]
Oh well, it's not just Auto wither, oops, the player utils really got changed for everything

**Comment by C10udburst** [comment]
minegame broke everything

**Comment by Epik123** [comment]
Tf auto wither wasnt a reject tho

**Comment by necrophili** [comment]
> minegame broke everything

Cry (Rip Inv utils)

**Comment by StormyBytes** [comment]
> Tf auto wither wasnt a reject tho still appreciate it being in there early tho:)

We also include non merged PRs

**Comment by C10udburst** [comment]
@necrophili please check if issue still occurs in the newest build

**Comment by StormyBytes** [comment]
@necrophili does the issue no longer occur? I'm assuming it no longer does because you closed it.
