### ISSUE TITLE
Some cool enhancements

### ISSUE THREAD

**Issue by Epik123** [C10udburst/meteor-rejects#9]
Target strafe it's like the random tp feature but it can either have ka on or off and it will still work on most clients it renders a ring around the enemy player and maker u can either sprint run or use speed to quickly rotate around said person while hitting them
Mabye the crasher from this video https://youtu.be/8Wu53S9LmFY

Phase and boat phase with a bypass
And noclip

Mabye infinity aura

**Comment by StormyBytes** [comment]
iirc theres a crashes addon which has alot of crashing methods. Why not try that?

**Comment by StormyBytes** [comment]
Found it, https://github.com/Wide-Cat/meteor-crash-addon

**Comment by C10udburst** [comment]
> Target strafe it's like the random tp feature but it can either have ka on or off and it will still work on most clients it renders a ring around the enemy player and maker u can either sprint run or use speed to quickly rotate around said person while hitting them

Isn't this similar to #4 ?

> Mabye the crasher from this video https://youtu.be/8Wu53S9LmFY

[meteor-crash-addon](https://github.com/Wide-Cat/meteor-crash-addon) has a boat crash idk if it's the same one

What's the difference between Phase and noclip?

> boat phase with a bypass

Boat phase is already a thing in this addon. Idk what do you want to bypass though

**Comment by Epik123** [comment]
> > Target strafe it's like the random tp feature but it can either have ka on or off and it will still work on most clients it renders a ring around the enemy player and maker u can either sprint run or use speed to quickly rotate around said person while hitting them
> 
> Isn't this similar to #4 ?
> 
> > Mabye the crasher from this video https://youtu.be/8Wu53S9LmFY
> 
> [meteor-crash-addon](https://github.com/Wide-Cat/meteor-crash-addon) has a boat crash idk if it's the same one
> 
> What's the difference between Phase and noclip?
> 
> > boat phase with a bypass
> 
> Boat phase is already a thing in this addon. Idk what do you want to bypass though

Tbh didnt know #4 already got implemented and the difference between phase and noclip is phase u cant go down and up only sideways also I'll check out that crash addon

**Comment by StormyBytes** [comment]
> the difference between phase and noclip is phase u cant go down and up only sideways 
Why would you need to seperate them?

**Comment by Epik123** [comment]
> > the difference between phase and noclip is phase u cant go down and up only sideways
> 
> Why would you need to seperate them?

I mean u dont need to separate them but the addon has neither it only has boatphase that doesnt really work even on vanilla servers

**Comment by C10udburst** [comment]
> I mean u dont need to separate them but the addon has neither it only has boatphase that doesnt really work even on vanilla servers

 I looked into it and tried adding phase/noclip. It doesn't even work on singleplayer, let alone multiplayer
